// <auto-generated />
using System;
using FH.Host.API.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FH.Host.API.Infrastructure.Migrations
{
    [DbContext(typeof(FangHuaHostDbContext))]
    [Migration("20201029004841_Add_Table_FH_BackGroundImageInfo")]
    partial class Add_Table_FH_BackGroundImageInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FH.Host.API.Model.DefaultEntity.FH_Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminName")
                        .IsRequired();

                    b.Property<string>("AdminPwd")
                        .IsRequired();

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("FH_Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminName = "Admin",
                            AdminPwd = "Admin123456",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 919, DateTimeKind.Local).AddTicks(886),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 920, DateTimeKind.Local).AddTicks(4796)
                        },
                        new
                        {
                            Id = 2,
                            AdminName = "Mr.Fang",
                            AdminPwd = "Fh2269...",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 920, DateTimeKind.Local).AddTicks(5985),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 920, DateTimeKind.Local).AddTicks(5987)
                        });
                });

            modelBuilder.Entity("FH.Host.API.Model.DefaultEntity.FH_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPwd")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("FH_Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 920, DateTimeKind.Local).AddTicks(9141),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 920, DateTimeKind.Local).AddTicks(9143),
                            UserName = "Admin",
                            UserPwd = "Admin123456"
                        },
                        new
                        {
                            Id = 2,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(111),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(114),
                            UserName = "Mr.Fang",
                            UserPwd = "Fh2269..."
                        });
                });

            modelBuilder.Entity("FH.Host.API.Model.ModelEntity.FH_BackGroundImageInfo", b =>
                {
                    b.Property<int>("BGId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BGUrl");

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("BGId");

                    b.ToTable("FH_BackGroundImageInfo");

                    b.HasData(
                        new
                        {
                            BGId = 1,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg1.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(3651),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(3652)
                        },
                        new
                        {
                            BGId = 2,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg2.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4342),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4344)
                        },
                        new
                        {
                            BGId = 3,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg3.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4373),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4374)
                        },
                        new
                        {
                            BGId = 4,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg4.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4436),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4436)
                        },
                        new
                        {
                            BGId = 5,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg5.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4450),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4451)
                        },
                        new
                        {
                            BGId = 6,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg6.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4465),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4465)
                        },
                        new
                        {
                            BGId = 7,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg7.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4477),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4477)
                        },
                        new
                        {
                            BGId = 8,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg8.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4489),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4489)
                        },
                        new
                        {
                            BGId = 9,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg9.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4500),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4501)
                        },
                        new
                        {
                            BGId = 10,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg10.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4513),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4513)
                        },
                        new
                        {
                            BGId = 11,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg11.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4525),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4526)
                        },
                        new
                        {
                            BGId = 12,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg12.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4537),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4538)
                        },
                        new
                        {
                            BGId = 13,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg13.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4549),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4549)
                        },
                        new
                        {
                            BGId = 14,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg14.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4561),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4561)
                        },
                        new
                        {
                            BGId = 15,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg15.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4572),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4573)
                        },
                        new
                        {
                            BGId = 16,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg16.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4584),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4584)
                        },
                        new
                        {
                            BGId = 17,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg17.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4595),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4596)
                        },
                        new
                        {
                            BGId = 18,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg18.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4650),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4651)
                        },
                        new
                        {
                            BGId = 19,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg19.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4662),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4662)
                        },
                        new
                        {
                            BGId = 20,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg20.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4673),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4674)
                        },
                        new
                        {
                            BGId = 21,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg21.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4685),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4686)
                        },
                        new
                        {
                            BGId = 22,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg22.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4696),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4697)
                        },
                        new
                        {
                            BGId = 23,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg23.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4708),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4708)
                        },
                        new
                        {
                            BGId = 24,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg24.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4720),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4720)
                        },
                        new
                        {
                            BGId = 25,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg25.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4731),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4732)
                        },
                        new
                        {
                            BGId = 26,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg26.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4743),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4743)
                        },
                        new
                        {
                            BGId = 27,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg27.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4754),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4754)
                        },
                        new
                        {
                            BGId = 28,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg28.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4766),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4766)
                        },
                        new
                        {
                            BGId = 29,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg29.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4777),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4777)
                        },
                        new
                        {
                            BGId = 30,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg30.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4789),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4789)
                        },
                        new
                        {
                            BGId = 31,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg31.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4861),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4861)
                        },
                        new
                        {
                            BGId = 32,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg32.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4873),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4873)
                        },
                        new
                        {
                            BGId = 33,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg33.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4884),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4884)
                        },
                        new
                        {
                            BGId = 34,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg34.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4897),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4897)
                        },
                        new
                        {
                            BGId = 35,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg35.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4908),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4908)
                        },
                        new
                        {
                            BGId = 36,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg36.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4919),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4920)
                        },
                        new
                        {
                            BGId = 37,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg37.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4931),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4931)
                        },
                        new
                        {
                            BGId = 38,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg38.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4942),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4943)
                        },
                        new
                        {
                            BGId = 39,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg39.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4953),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4954)
                        },
                        new
                        {
                            BGId = 40,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg40.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4965),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4965)
                        },
                        new
                        {
                            BGId = 41,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg41.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4976),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4976)
                        },
                        new
                        {
                            BGId = 42,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg42.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4987),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4988)
                        },
                        new
                        {
                            BGId = 43,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg43.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4998),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(4999)
                        },
                        new
                        {
                            BGId = 44,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg44.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5037),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5038)
                        },
                        new
                        {
                            BGId = 45,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg45.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5049),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5049)
                        },
                        new
                        {
                            BGId = 46,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg46.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5060),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5061)
                        },
                        new
                        {
                            BGId = 47,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg47.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5072),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5072)
                        },
                        new
                        {
                            BGId = 48,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg48.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5083),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5083)
                        },
                        new
                        {
                            BGId = 49,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg49.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5094),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5095)
                        },
                        new
                        {
                            BGId = 50,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg50.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5106),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5106)
                        },
                        new
                        {
                            BGId = 51,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg51.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5117),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5118)
                        },
                        new
                        {
                            BGId = 52,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg52.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5128),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5129)
                        },
                        new
                        {
                            BGId = 53,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg53.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5140),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5140)
                        },
                        new
                        {
                            BGId = 54,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg54.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5151),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5152)
                        },
                        new
                        {
                            BGId = 55,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg55.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5162),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5163)
                        },
                        new
                        {
                            BGId = 56,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg56.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5174),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5174)
                        },
                        new
                        {
                            BGId = 57,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg57.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5219),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5219)
                        },
                        new
                        {
                            BGId = 58,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg58.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5232),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5232)
                        },
                        new
                        {
                            BGId = 59,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg59.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5243),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5244)
                        },
                        new
                        {
                            BGId = 60,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg60.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5255),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5255)
                        },
                        new
                        {
                            BGId = 61,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg61.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5266),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5267)
                        },
                        new
                        {
                            BGId = 62,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg62.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5277),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5278)
                        },
                        new
                        {
                            BGId = 63,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg63.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5289),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5289)
                        },
                        new
                        {
                            BGId = 64,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg64.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5300),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5301)
                        },
                        new
                        {
                            BGId = 65,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg65.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5312),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5312)
                        },
                        new
                        {
                            BGId = 66,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg66.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5324),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5325)
                        },
                        new
                        {
                            BGId = 67,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg67.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5336),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5336)
                        },
                        new
                        {
                            BGId = 68,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg68.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5347),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5348)
                        },
                        new
                        {
                            BGId = 69,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg69.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5385),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5386)
                        },
                        new
                        {
                            BGId = 70,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg70.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5411),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5411)
                        },
                        new
                        {
                            BGId = 71,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg71.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5423),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5423)
                        },
                        new
                        {
                            BGId = 72,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg72.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5434),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5435)
                        },
                        new
                        {
                            BGId = 73,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg73.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5446),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5446)
                        },
                        new
                        {
                            BGId = 74,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg74.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5457),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5458)
                        },
                        new
                        {
                            BGId = 75,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg75.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5468),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5469)
                        },
                        new
                        {
                            BGId = 76,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg76.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5480),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5481)
                        },
                        new
                        {
                            BGId = 77,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg77.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5491),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5492)
                        },
                        new
                        {
                            BGId = 78,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg78.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5503),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5503)
                        },
                        new
                        {
                            BGId = 79,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg79.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5514),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5515)
                        },
                        new
                        {
                            BGId = 80,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg80.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5525),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5526)
                        },
                        new
                        {
                            BGId = 81,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg81.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5537),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5537)
                        },
                        new
                        {
                            BGId = 82,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg82.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5548),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5549)
                        },
                        new
                        {
                            BGId = 83,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg83.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5591),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5592)
                        },
                        new
                        {
                            BGId = 84,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg84.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5602),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5603)
                        },
                        new
                        {
                            BGId = 85,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg85.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5614),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5614)
                        },
                        new
                        {
                            BGId = 86,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg86.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5625),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5625)
                        },
                        new
                        {
                            BGId = 87,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg87.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5636),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5637)
                        },
                        new
                        {
                            BGId = 88,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg88.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5647),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5648)
                        },
                        new
                        {
                            BGId = 89,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg89.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5659),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5659)
                        },
                        new
                        {
                            BGId = 90,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg90.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5670),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5671)
                        },
                        new
                        {
                            BGId = 91,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg91.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5682),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5682)
                        },
                        new
                        {
                            BGId = 92,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg92.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5693),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5693)
                        },
                        new
                        {
                            BGId = 93,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg93.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5704),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5705)
                        },
                        new
                        {
                            BGId = 94,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg94.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5715),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5716)
                        },
                        new
                        {
                            BGId = 95,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg95.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5727),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5727)
                        },
                        new
                        {
                            BGId = 96,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg96.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5764),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5765)
                        },
                        new
                        {
                            BGId = 97,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg97.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5777),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5778)
                        },
                        new
                        {
                            BGId = 98,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg98.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5788),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5789)
                        },
                        new
                        {
                            BGId = 99,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg99.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5800),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            BGId = 100,
                            BGUrl = "http://objstorage.fanghua.host/assets/images/backGround/bg100.jpg",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5831),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(5831)
                        });
                });

            modelBuilder.Entity("FH.Host.API.Model.ModelEntity.FH_CopywritingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("FH_CopywritingInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "当你的能力还撑不起你的野心的时，你就需要静下心来 好好学习。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2488),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2489)
                        },
                        new
                        {
                            Id = 2,
                            Content = "脏的人多了，干净反倒成了一种错。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2982),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2983)
                        },
                        new
                        {
                            Id = 3,
                            Content = "你羡慕的生活都是你没熬过的苦。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2991),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2991)
                        },
                        new
                        {
                            Id = 4,
                            Content = "所谓天才，只不过是把别人喝咖啡的功夫都用在了工作上了。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2993),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2993)
                        },
                        new
                        {
                            Id = 5,
                            Content = "生活便是寻求新的知识。——门捷列夫",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2994),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2995)
                        },
                        new
                        {
                            Id = 6,
                            Content = "如果你浪费了自己的年龄，那是挺可悲的。因为你的青春只能持续一点儿时间——很短的一点儿时间。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2996),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2996)
                        },
                        new
                        {
                            Id = 7,
                            Content = "世界上一成不变的东西，只有“任何事物都是在不断变化的”这条真理。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(2999),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(3000)
                        });
                });

            modelBuilder.Entity("FH.Host.API.Model.ModelEntity.FH_EmailHistoryInfo", b =>
                {
                    b.Property<int>("EHID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<string>("EmailBody")
                        .IsRequired();

                    b.Property<string>("EmailCode");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("RecipientId")
                        .IsRequired();

                    b.HasKey("EHID");

                    b.ToTable("FH_EmailHistoryInfo");
                });

            modelBuilder.Entity("FH.Host.API.Model.ModelEntity.FH_GuidePagesMenuInfo", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("MenuName")
                        .IsRequired();

                    b.Property<int>("MenuOrder");

                    b.Property<string>("MenuUrl")
                        .IsRequired();

                    b.Property<int>("ParentId");

                    b.HasKey("MenuID");

                    b.ToTable("FH_GuidePagesMenuInfo");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(896),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(898),
                            MenuName = "Mr.Fang♥Mrs.Zhou",
                            MenuOrder = 1,
                            MenuUrl = "https://love.fanghua.host",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 2,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(1841),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(1842),
                            MenuName = "首页",
                            MenuOrder = 2,
                            MenuUrl = "https://home.fanghua.host",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 3,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(1857),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(1858),
                            MenuName = "QQ",
                            MenuOrder = 3,
                            MenuUrl = "https://wpa.qq.com/msgrd?v=3&uin=2875616188&site=qq&menu=yes",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 4,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(1859),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(1860),
                            MenuName = "微信",
                            MenuOrder = 4,
                            MenuUrl = "https://fanghua.host/assets/images/weixin.jpg",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 5,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(1861),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(1863),
                            MenuName = "实用小工具",
                            MenuOrder = 5,
                            MenuUrl = "https://tool.fanghua.host",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 6,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(1864),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 29, 8, 48, 40, 921, DateTimeKind.Local).AddTicks(1865),
                            MenuName = "休闲小游戏",
                            MenuOrder = 6,
                            MenuUrl = "https://game.fanghua.host",
                            ParentId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
