// <auto-generated />
using System;
using FH.Host.API.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FH.Host.API.Infrastructure.Migrations
{
    [DbContext(typeof(FangHuaHostDbContext))]
    [Migration("20201017072322_Add_Table_FH_EmailHistoryInfo")]
    partial class Add_Table_FH_EmailHistoryInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FH.Host.API.Model.DefaultEntity.FH_Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminName")
                        .IsRequired();

                    b.Property<string>("AdminPwd")
                        .IsRequired();

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("FH_Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminName = "Admin",
                            AdminPwd = "Admin123456",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 143, DateTimeKind.Local).AddTicks(2964),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 145, DateTimeKind.Local).AddTicks(3108)
                        },
                        new
                        {
                            Id = 2,
                            AdminName = "Mr.Fang",
                            AdminPwd = "Fh2269...",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 145, DateTimeKind.Local).AddTicks(5879),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 145, DateTimeKind.Local).AddTicks(5884)
                        });
                });

            modelBuilder.Entity("FH.Host.API.Model.DefaultEntity.FH_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.Property<string>("UserPwd")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("FH_Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 145, DateTimeKind.Local).AddTicks(9858),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 145, DateTimeKind.Local).AddTicks(9863),
                            UserName = "Admin",
                            UserPwd = "Admin123456"
                        },
                        new
                        {
                            Id = 2,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(1230),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(1232),
                            UserName = "Mr.Fang",
                            UserPwd = "Fh2269..."
                        });
                });

            modelBuilder.Entity("FH.Host.API.Model.ModelEntity.FH_CopywritingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.HasKey("Id");

                    b.ToTable("FH_CopywritingInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "当你的能力还撑不起你的野心的时，你就需要静下心来 好好学习。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(4818),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(4820)
                        },
                        new
                        {
                            Id = 2,
                            Content = "脏的人多了，干净反倒成了一种错。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5962),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5967)
                        },
                        new
                        {
                            Id = 3,
                            Content = "你羡慕的生活都是你没熬过的苦。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5978),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5979)
                        },
                        new
                        {
                            Id = 4,
                            Content = "所谓天才，只不过是把别人喝咖啡的功夫都用在了工作上了。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5980),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5981)
                        },
                        new
                        {
                            Id = 5,
                            Content = "生活便是寻求新的知识。——门捷列夫",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5981),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5982)
                        },
                        new
                        {
                            Id = 6,
                            Content = "如果你浪费了自己的年龄，那是挺可悲的。因为你的青春只能持续一点儿时间——很短的一点儿时间。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5983),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5984)
                        },
                        new
                        {
                            Id = 7,
                            Content = "世界上一成不变的东西，只有“任何事物都是在不断变化的”这条真理。",
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5985),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(5985)
                        });
                });

            modelBuilder.Entity("FH.Host.API.Model.ModelEntity.FH_EmailHistoryInfo", b =>
                {
                    b.Property<int>("EHID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<string>("EmailBody")
                        .IsRequired();

                    b.Property<string>("EmailCode");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("RecipientId")
                        .IsRequired();

                    b.HasKey("EHID");

                    b.ToTable("FH_EmailHistoryInfo");
                });

            modelBuilder.Entity("FH.Host.API.Model.ModelEntity.FH_GuidePagesMenuInfo", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreateAdminID");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("CreateUserID");

                    b.Property<string>("DeleteTimeAndRemark");

                    b.Property<int>("IsDeleted");

                    b.Property<DateTime>("LastUpdateTime");

                    b.Property<string>("MenuName")
                        .IsRequired();

                    b.Property<int>("MenuOrder");

                    b.Property<string>("MenuUrl")
                        .IsRequired();

                    b.Property<int>("ParentId");

                    b.HasKey("MenuID");

                    b.ToTable("FH_GuidePagesMenuInfo");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(2261),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(2264),
                            MenuName = "首页",
                            MenuOrder = 1,
                            MenuUrl = "https://home.fanghua.host",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 2,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3902),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3904),
                            MenuName = "QQ",
                            MenuOrder = 2,
                            MenuUrl = "https://wpa.qq.com/msgrd?v=3&uin=2875616188&site=qq&menu=yes",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 3,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3920),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3922),
                            MenuName = "微信",
                            MenuOrder = 3,
                            MenuUrl = "https://fanghua.host/assets/images/weixin.jpg",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 4,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3924),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3925),
                            MenuName = "Mr.Fang♥Mrs.Zhou",
                            MenuOrder = 4,
                            MenuUrl = "https://fh.fanghua.host",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 5,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3926),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3927),
                            MenuName = "表白小工具",
                            MenuOrder = 5,
                            MenuUrl = "https://devlove.fanghua.host",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 6,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3929),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3930),
                            MenuName = "实用小工具",
                            MenuOrder = 6,
                            MenuUrl = "https://tool.fanghua.host",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 7,
                            CreateAdminID = 0,
                            CreateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3986),
                            CreateUserID = 0,
                            IsDeleted = 0,
                            LastUpdateTime = new DateTime(2020, 10, 17, 15, 23, 22, 146, DateTimeKind.Local).AddTicks(3986),
                            MenuName = "休闲小游戏",
                            MenuOrder = 7,
                            MenuUrl = "https://game.fanghua.host",
                            ParentId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
